# Generated by Django 5.1.2 on 2024-10-11 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lulu_teacher', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
