# Generated by Django 5.1.2 on 2024-10-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lulu_teacher', '0003_alter_historicalsessions_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsessions',
            name='ID',
        ),
        migrations.AddField(
            model_name='historicalsessions',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
