# Generated by Django 5.1.2 on 2024-10-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lulu_teacher', '0005_lulutrainning_alter_historicalsessions_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsessions',
            name='sessionDate',
            field=models.DateTimeField(default='', verbose_name='session date'),
        ),
    ]
